<a href="https://colab.research.google.com/github/KamranRiyaz/MachineLearning-Using-Python/blob/main/ANN_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
%pip install ucimlrepo

In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

# Importing the DataSet

In [46]:
from ucimlrepo import fetch_ucirepo
dataset = fetch_ucirepo(id=294)

In [47]:
X = dataset.data.features.values
y = dataset.data.targets.values

In [48]:
print(dataset.metadata)

{'uci_id': 294, 'name': 'Combined Cycle Power Plant', 'repository_url': 'https://archive.ics.uci.edu/dataset/294/combined+cycle+power+plant', 'data_url': 'https://archive.ics.uci.edu/static/public/294/data.csv', 'abstract': 'The dataset contains 9568 data points collected from a Combined Cycle Power Plant over 6 years (2006-2011), when the plant was set to work with full load. ', 'area': 'Computer Science', 'tasks': ['Regression'], 'characteristics': ['Multivariate'], 'num_instances': 9568, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['PE'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2014, 'last_updated': 'Mon Mar 04 2024', 'dataset_doi': '10.24432/C5002N', 'creators': ['Pnar Tfekci', 'Heysem Kaya'], 'intro_paper': {'ID': 406, 'type': 'NATIVE', 'title': 'Prediction of full load electrical power output of a base load operated combined cycle power plant using machine learning methods', 'aut

In [49]:
print(dataset.variables)

  name     role        type demographic                          description  \
0   AT  Feature  Continuous        None      in the range 1.81°C and 37.11°C   
1    V  Feature  Continuous        None       in teh range 25.36-81.56 cm Hg   
2   AP  Feature  Continuous        None  in the range 992.89-1033.30 milibar   
3   RH  Feature  Continuous        None       in the range 25.56% to 100.16%   
4   PE   Target  Continuous        None                     420.26-495.76 MW   

     units missing_values  
0        C             no  
1    cm Hg             no  
2  milibar             no  
3        %             no  
4       MW             no  


#

# Data Preprocessing

## Train-Test Split


In [50]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [51]:
print(X_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [52]:
print(X_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


In [53]:
print(y_train)

[[473.93]
 [467.87]
 [431.97]
 ...
 [459.01]
 [462.72]
 [428.12]]


In [54]:
print(y_test)

[[431.23]
 [460.01]
 [461.14]
 ...
 [473.26]
 [438.  ]
 [463.28]]


## Feature Scaling

# Building the ANN

##1. Initialising the ANN

In [55]:
ann = tf.keras.models.Sequential()

##2. Add input and first layer

In [56]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

##3 Add the Second Hidden layer

In [57]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

##3. Add OutPut layer

In [58]:
ann.add(tf.keras.layers.Dense(units = 1))

# Training the ANN

##1. Compiling the ANN

In [59]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

##2. Training the ANN

In [60]:
ann.fit(X,y,batch_size = 32, epochs = 50)

Epoch 1/50
299/299 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 95087.2344
Epoch 2/50
299/299 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 451.3040
Epoch 3/50
299/299 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 427.5566
Epoch 4/50
299/299 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 400.6049
Epoch 5/50
299/299 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 373.6179
Epoch 6/50
299/299 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 337.3067
Epoch 7/50
299/299 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 308.7751
Epoch 8/50
299/299 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 281.4856
Epoch 9/50
299/299 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 249.2132
Epoch 10/50
299/299 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 225.4175
Epoch 11/50
299/299 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 192.0605
Epoch 12/50
299/299 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 169.4143
Epoch 13/50
299/299 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 146.6046
Epoch 14/50
299/299 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 124.3290
Epoch 15/50
299/299 ━━━━━━━

# Predicting the Output

In [61]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision = 2)
y_pred.reshape(len(y_pred),1)
y_test.reshape(len(y_pred),1)
print(np.concatenate((y_pred, y_test),1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
[[430.54 431.23]
 [461.98 460.01]
 [465.66 461.14]
 ...
 [472.59 473.26]
 [439.87 438.  ]
 [458.9  463.28]]
