<a href="https://colab.research.google.com/github/KamranRiyaz/MachineLearning-Using-Python/blob/main/ANN_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%pip install ucimlrepo

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

# Importing the DataSet

In [6]:
from ucimlrepo import fetch_ucirepo
dataset = fetch_ucirepo(id=294)

In [23]:
X = dataset.data.features.values
y = dataset.data.targets.values

In [24]:
print(dataset.metadata)

{'uci_id': 294, 'name': 'Combined Cycle Power Plant', 'repository_url': 'https://archive.ics.uci.edu/dataset/294/combined+cycle+power+plant', 'data_url': 'https://archive.ics.uci.edu/static/public/294/data.csv', 'abstract': 'The dataset contains 9568 data points collected from a Combined Cycle Power Plant over 6 years (2006-2011), when the plant was set to work with full load. ', 'area': 'Computer Science', 'tasks': ['Regression'], 'characteristics': ['Multivariate'], 'num_instances': 9568, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['PE'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2014, 'last_updated': 'Mon Mar 04 2024', 'dataset_doi': '10.24432/C5002N', 'creators': ['Pnar Tfekci', 'Heysem Kaya'], 'intro_paper': {'ID': 406, 'type': 'NATIVE', 'title': 'Prediction of full load electrical power output of a base load operated combined cycle power plant using machine learning methods', 'aut

In [9]:
print(dataset.variables)

  name     role        type demographic                          description  \
0   AT  Feature  Continuous        None      in the range 1.81°C and 37.11°C   
1    V  Feature  Continuous        None       in teh range 25.36-81.56 cm Hg   
2   AP  Feature  Continuous        None  in the range 992.89-1033.30 milibar   
3   RH  Feature  Continuous        None       in the range 25.56% to 100.16%   
4   PE   Target  Continuous        None                     420.26-495.76 MW   

     units missing_values  
0        C             no  
1    cm Hg             no  
2  milibar             no  
3        %             no  
4       MW             no  


#

# Data Preprocessing

## Train-Test Split


In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [26]:
print(X_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [27]:
print(X_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


In [28]:
print(y_train)

[[473.93]
 [467.87]
 [431.97]
 ...
 [459.01]
 [462.72]
 [428.12]]


In [29]:
print(y_test)

[[431.23]
 [460.01]
 [461.14]
 ...
 [473.26]
 [438.  ]
 [463.28]]


## Feature Scaling

In [30]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Building the ANN

##1. Initialising the ANN

In [41]:
ann = tf.keras.models.Sequential()

##2. Add input and first layer

In [42]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

##3 Add the Second Hidden layer

In [43]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

##3. Add OutPut layer

In [44]:
ann.add(tf.keras.layers.Dense(units = 1,))

# Training the ANN

##1. Compiling the ANN

In [45]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['mae', 'mse'])

##2. Training the ANN

In [46]:
ann.fit(X,y,batch_size = 32, epochs = 100)

Epoch 1/40
299/299 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 454432.3750 - mae: 665.6159 - mse: 454432.3750
Epoch 2/40
299/299 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 206443.0938 - mae: 454.0433 - mse: 206443.0938
Epoch 3/40
299/299 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 206183.5000 - mae: 453.7522 - mse: 206183.5000
Epoch 4/40
299/299 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 205609.7656 - mae: 453.1224 - mse: 205609.7656
Epoch 5/40
299/299 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 205814.1250 - mae: 453.3416 - mse: 205814.1250
Epoch 6/40
299/299 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 205601.0469 - mae: 453.1091 - mse: 205601.0469
Epoch 7/40
299/299 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 205106.0469 - mae: 452.5638 - mse: 205106.0469
Epoch 8/40
299/299 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 205049.6719 - mae: 452.4997 - mse: 205049.6719
Epoch 9/40
299/299 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 204564.2188 - mae: 451.9606 - mse: 204564.2188
Epoch 10/40
299/299 ━━━━━━━━━━━━━━━━━

# Predicting the Output

In [47]:
y_pred = ann.predict(X_test)
print(y_pred)

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
[[11.779493]
 [11.404682]
 [11.389269]
 ...
 [11.410903]
 [11.7541  ]
 [11.68887 ]]
